name: Build Docker image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-18.04
    strategy:
      matrix:
        docfx_version: [2.50]

    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build . --file Dockerfile --build-arg DOCFX_VERSION=${{ matrix.docfx_version }} --tag docker.pkg.github.com/combinationab/docfx-docker:${{ matrix.docfx_version }}
    - name: Push Docker image
      run: docker push docker.pkg.github.com/combinationab/docfx-docker:${{ matrix.docfx_version }}
